version: '3'

services:
  postgres:
    image: postgres:12.4
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    hostname: postgres
    restart: always
   
  pgadmin:
    image: dpage/pgadmin4:4.25
    container_name: pgadmin
    ports:
      - 8080:80
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./postgres/admin:/var/lib/pgadmin/storage
    hostname: pgadmin
    restart: always

  backend:
    build: ./backend/docker
    container_name: backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/c_timer
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend:cached
      - cargo-cache:/usr/local/cargo/registry
    command: bash -c 'diesel setup && cargo watch -x run'
  
  frontend:
    build: ./frontend/docker
    container_name: frontend
    ports:
      - 80:8080
    privileged: true
    volumes:
      - ./frontend:/frontend:cached
    depends_on:
      - backend
    command: yarn serve

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 81:8080
    privileged: true
    environment:
      SWAGGER_JSON: swagger.json
    volumes:
      - ./swagger/swagger.json:/usr/share/nginx/html/swagger.json:cached


volumes:
  db:
    driver: local
  cargo-cache:
    driver: local
